<?php

namespace lelycan\indexBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * fichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fichierRepository extends EntityRepository
{
}
