<?php

namespace lelycan\indexBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * projetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class projetRepository extends EntityRepository
{
    public function loadAll($id)
    {
        $querybuilder = $this->createQueryBuilder('a')
                             ->where('a.id = :id')
                             ->leftJoin('a.fichiers', 'c')
                             ->addSelect('c')
                             ->leftJoin('c.uploads', 'd')
                             ->addSelect('d')
                             ->setParameter('id',$id)
                             ->leftJoin('a.commentaires', 'e')
                             ->addSelect('e')
                             ->orderBy('c.date','DESC');
        
        return  $querybuilder->getQuery()
                             ->getOneOrNullResult();
    }
}
