<?php

namespace Abbaye\IndexBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencesRepository extends EntityRepository
{
}
