<?php

namespace Abbaye\IndexBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FlashNewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlashNewRepository extends EntityRepository
{
    public function FlashFindTen()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb ->select('a')
            ->from('AbbayeIndexBundle:FlashNew', 'a')
            ->orderBy('a.date','DESC')
			->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }
	
	    public function FlashFindAll()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb ->select('a')
            ->from('AbbayeIndexBundle:FlashNew', 'a')
            ->orderBy('a.date','DESC');
        return $qb->getQuery()->getResult();
    }
}
