jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha512
            iterations: 1
            encode_as_base64: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: oRxdCfXxzyNgkJFinQ1GHgPmXF4WQOTOpj72d99WXR2FqNjQZEirlipX0TMHfQERE07j5G43QWjF1QDCugxtew==, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true            
            provider: in_memory
            form_login:
                login_path: login
                check_path: loginCheck
            logout:
                path:       logout
                target:     /

    access_control:
        - { path: ^/!/admin, roles: ROLE_ADMIN}
