parameters:
#    lelycanindex.example.class: lelycan\indexBundle\Example

services:
#    lelycanindex.example:
#        class: %lelycanindex.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
