parameters:
#    abbaye_user.example.class: Abbaye\UserBundle\Example

services:
#    abbaye_user.example:
#        class: %abbaye_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
